language: R
cache: packages
warnings_are_errors: true
sudo: required

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libhdf5-dev

r_packages:
  - data.table
  - memuse
  - hdf5r
  - bit64

r_github_packages:
  - lineSampler
